services:
  postgres:
    image: postgres:16-alpine
    container_name: zapchast-postgres
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: zapchast
      POSTGRES_PASSWORD: zapchast
      POSTGRES_DB: zapchast
    volumes:
      - zapchast_pg_data:/var/lib/postgresql/data

volumes:
  zapchast_pg_data:
